export class DocMateInvoiceLine {
    constructor(
        public id: number = 0,
        public createdUtc: string = '',
        public filename: string | null = null,
        public docType: string | null = null,
        public supplierName: string | null = null,
        public customerName: string | null = null,
        public cmsCustomerId: string | null = null,
        public docNumber: string | null = null,
        public docDate: string | null = null,
        public lineNo: number | null = null,
        public code: string | null = null,
        public description: string | null = null,
        public casePack: number | null = null,
        public unitSize: string | null = null,
        public totalUnits: number | null = null,
        public qty: number | null = null,
        public unitPrice: number | null = null,
        public lineNet: number | null = null,
        public vatCode: string | null = null,
        public vatRate: number | null = null,
        public vatAmount: number | null = null,
        public lineGross: number | null = null,
        public stdRrp: number | null = null,
        public por: number | null = null,
        public isVoid: number | null = null,
        public voidNote: string | null = null,
        public pmp: number | null = null,
        public raw: string | null = null,
        public barcode: string | null = null,
        public unitCost: number | null = null,
        public compared: boolean | null = null,
        public generated: boolean | null = null,
        public startSync: boolean | null = null,
        public endSync: boolean | null = null,
        public originalId: number = 0
    ) { }
}